import java.io.*;
import java.security.*;
import java.security.cert.*;
import javax.crypto.*;
import javax.crypto.spec.*;

/*
    Simulates Alice's side of the communication. She wants to securely exchange messages 
    with Bruce, who has a certificate exposing his public key.

    The student's task is to implement the main and all the necessary function to
    complete the communication.

    This involves:
    1. Generating an EC key pair for Alice (keysize = 256).
    2. Getting Bruce's certificate from the provided PEM file, verifying it
        and extracting his public key.
    3. Sending Alice's public key to Bruce, along with a SHA256withECDSA signature of it.
    4. Perform the ECDH key agreement protocol to derive a shared secret, and then derive
        a symmetric key from it using SHA-256.
    5. Decrypt the message received from Bruce, and verify its integrity.
        The message has been encrypted using AES/GCM/NoPadding, with the shared secret key
        and no additional data.
        The IV for AES/GCM is generated by Bruce using a SHA1PRNG seeded with the
        Organizational Unit Name field of his certificate's subject DN, converted in bytes (16 bytes).
        The macsize is 128 bits.
    6. Send a message to Bruce, encrypted with the same symmetric key and AES/GCM/NoPadding.
        The IV should be generated randomly, and sent to Bruce along with the ciphertext.

    BRUCE'S SIDE:
    The code for Bruce is provided, and should not be modified.
    In order to communicate with Bruce, istantiate a Bruce object and call the
    following methods:
    - sendPublicKey(PublicKey alicePub, byte[] signature): sends Alice's public key to Bruce, 
        along with its ECDSA signature. Bruce will verify the signature and then 
        save Alice's public key for the ECDH protocol.
    - getMessage(): returns the encryption of the message sent by Bruce, encrypted 
        with AES/GCM/NoPadding, using the shared key.
    - sendMessage(byte[] ciphertext, GCMParameterSpec params): sends an encrypted
        message to Bruce, along with the GCM parameters used for encryption (IV and macsize).
        Returns true if Bruce successfully verified and decrypted the message, false otherwise.
*/

public class Alice {

    // Function to retrieve Bruce's certificate from the provided PEM file
    private static X509Certificate getCertificate(String filename) throws Exception {
        FileInputStream fis = new FileInputStream("./myCert.pem");
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        X509Certificate cert = (X509Certificate)cf.generateCertificate(fis);
        return cert;
    }

    // Function to verify and validate Bruce's certificate using its own public key
    private static boolean verifyCertificate(X509Certificate cert) {
        PublicKey pubKey= cert.getPublicKey();
        try{
            cert.verify(pubKey);
        }catch(Exception e){
            return false;
        }
        return true;
    }

    // Helper function to extract the OU field from the certificate's subject DN, used for IV generation
    private static String extractOrganizationalUnitName(String dn) {
        for (String entry : dn.split(",")) {
            if (entry.trim().startsWith("OU=")) {
                return entry.trim().substring(3);
            }
        }
        return "";
    }

    // Function to generate GCM parameters (IV and macsize) for decryption
    // Note: Use extractOrganizationalUnitName to get the OU field from
    //  the certificate's subject DN and generate the correct IV.
    private static GCMParameterSpec getGCMParams(X509Certificate cert) throws Exception {
        String dn = cert.getSubjectDN().toString();
        String ou = extractOrganizationalUnitName(dn);
        byte[] ouBytes = ou.getBytes();
        
        SecureRandom sr = SecureRandom.getInstance("SHA1PRNG");
        sr.setSeed(ouBytes);
        byte[] iv = new byte[16];
        sr.nextBytes(iv);
        
        return new GCMParameterSpec(128, iv);
    }

    public static void main(String[] args) {
        try {

            Bruce bruce = new Bruce();

            // ALICE INITIALIZATION
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("EC");
            keyGen.initialize(256);
            KeyPair aliceKeyPair = keyGen.generateKeyPair();
            PrivateKey alicePrivate = aliceKeyPair.getPrivate();
            PublicKey alicePublic = aliceKeyPair.getPublic();

            // GET BRUCE CERTIFICATE
            X509Certificate bruceCert = getCertificate("./myCert.pem");

            // VERIFY BRUCE CERTIFICATE
            if (!verifyCertificate(bruceCert)) {
                throw new Exception("Certificate verification failed");
            }

            // SEND ALICE PUBLIC KEY TO BRUCE WITH ECDSA SIGNATURE
            Signature sig = Signature.getInstance("SHA256withECDSA");
            sig.initSign(alicePrivate);
            sig.update(alicePublic.getEncoded());
            byte[] signature = sig.sign();
            bruce.sendPublicKey(alicePublic, signature);

            // DIFFIE-HELLMAN KEY EXCHANGE
            KeyAgreement keyAgreement = KeyAgreement.getInstance("ECDH");
            keyAgreement.init(alicePrivate);
            PublicKey brucePublic = bruceCert.getPublicKey();
            keyAgreement.doPhase(brucePublic, true);
            byte[] sharedSecret = keyAgreement.generateSecret();

            // KEY DERIVATION
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] derivedKey = md.digest(sharedSecret);
            SecretKey aesKey = new SecretKeySpec(derivedKey, "AES");

            // VERIFY/DECRYPT BRUCE MESSAGE
            GCMParameterSpec gcmParams = getGCMParams(bruceCert);
            byte[] encryptedMessage = bruce.getMessage();
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, aesKey, gcmParams);
            byte[] decryptedMessage = cipher.doFinal(encryptedMessage);
            System.out.println("Decrypted message from Bruce: " + new String(decryptedMessage));

            // SEND MESSAGE TO BRUCE
            String message = "Hello Bruce!";
            SecureRandom random = new SecureRandom();
            byte[] iv = new byte[16];
            random.nextBytes(iv);
            GCMParameterSpec sendParams = new GCMParameterSpec(128, iv);
            cipher.init(Cipher.ENCRYPT_MODE, aesKey, sendParams);
            byte[] ciphertext = cipher.doFinal(message.getBytes());
            boolean success = bruce.sendMessage(ciphertext, sendParams);
            System.out.println("Message sent successfully: " + success);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
}